/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package socialmedia;

/**
 *
 * @author anishgautam
 */
public class settings extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(settings.class.getName());

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 1, 36)); // NOI18N
        jLabel1.setText("SETTING");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 60, 170, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account_circle.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 170, 30, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Shield.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 230, 30, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/diamond_svgrepo.com.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 290, 35, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Paperclip.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 350, 30, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bug_svgrepo.com.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 410, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Help circle.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 470, 30, 30);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel8.setText("Account");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 167, 110, 40);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel9.setText("Security and account access");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 210, 332, 70);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel10.setText("Membership");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 270, 144, 70);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel11.setText("Privacy and Safety");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(150, 340, 212, 60);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel12.setText("Report a Bug");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 400, 152, 50);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel13.setText("Help and Support");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(150, 460, 202, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new settings().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
